api_platform:
    title: 'Jamly API'
    description: 'API documentation of Jamly'
    version: '1.0.0'
    formats:
      json: ['application/json']
    error_formats:
      json: ["application/json"]
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
