api_platform:
    title: 'Jamly API'
    description: 'API documentation of Jamly'
    version: '1.0.0'
    formats:
        json: ['application/json']
    error_formats:
        json: ["application/json"]
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/ApiResource'
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        pagination_items_per_page: 20
        pagination_enabled: true
        normalization_context:
            skip_null_values: false
            enable_max_depth: true