services:
  php:
    build:
      context: .
      target: frankenphp_dev
    container_name: jamly-api
    image: app-php
    restart: unless-stopped
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}&charset=${POSTGRES_CHARSET}
      # Spotify Integration
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
      SPOTIFY_AUTH_URL: ${SPOTIFY_AUTH_URL}
      SPOTIFY_TOKEN_URL: ${SPOTIFY_TOKEN_URL}
      SPOTIFY_API_URL: ${SPOTIFY_API_URL}
    volumes:
      - caddy_data:/data:z
      - caddy_config:/config:z
      - .:/app:z
      - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro,z
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443


# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service

###> doctrine/doctrine-bundle ###
  database:
    container_name: jamly-database
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw,z
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  caddy_data:
  caddy_config:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
