# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # HTTP Clients Configuration
    spotify.api.client:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: ['@http_client', 'withOptions']
        arguments:
            - base_uri: 'https://api.spotify.com/v1/'
              headers:
                'Accept': 'application/json'
                'Content-Type': 'application/json'

    spotify.auth.client:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: ['@http_client', 'withOptions']
        arguments:
            - headers:
                'Content-Type': 'application/x-www-form-urlencoded'
                'Accept': 'application/json'

    # Spotify Services Configuration
    App\Service\Spotify\SpotifyAuthService:
        arguments:
            $spotifyApiClient: '@spotify.api.client'
            $spotifyAuthClient: '@spotify.auth.client'
            $entityManager: '@doctrine.orm.entity_manager'
            $clientId: '%env(SPOTIFY_CLIENT_ID)%'
            $redirectUri: '%env(SPOTIFY_REDIRECT_URI)%'

    App\Service\Spotify\SpotifyService:
        arguments:
            $spotifyApiClient: '@spotify.api.client'
