name: AutoPR CI
run-name: "ðŸ”€ [${{ github.workflow }} #${{ github.run_number }}] ${{ github.ref_name }} by @${{ github.actor }}"

on:
  push:
    branches-ignore:
      - staging
      - main
  workflow_dispatch:

jobs:
  auto-pr:
    uses: T-ESP-ASSTAGJ/infra/.github/workflows/reusable-autopr.yml@main
    with:
      repository_name: "api"
      dev_branch: "staging"
      prod_branch: "main"
      dev_tag: "#STAGING"
      prod_tag: "#MASTER"
      trad_tag: "#TRAD"
      reviewers: "tlebeau13,SergioMiGuPr"
    secrets:
      GITHUB_TOKEN: ${{ secrets.AUTO_DEPLOY_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.PR_BACK_REMINDER_WEBHOOK_URL }}